language: php

php:
- 7.3

sudo: false

env:
  global:
    - PLUGIN_NAME=FroshPlatformAdminer

stages:
    - name: Store-Check
      if: tag IS blank AND env(PLUGIN_ID) IS present AND type != pull_request
    - name: Store-Sync
      if: branch = master AND env(PLUGIN_ID) IS present AND type != pull_request
    - name: Store-Deploy
      if: tag IS present

jobs:
    include:
        - stage: Store-Check
          php: 7.3
          before_script: skip
          install:
              - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.1/frosh-plugin-upload.phar' -O /tmp/frosh-plugin-upload.phar
              - cd /tmp && php /tmp/frosh-plugin-upload.phar plugin:zip:dir ${TRAVIS_BUILD_DIR} && mv ${PLUGIN_NAME}*.zip ${TRAVIS_BUILD_DIR}
          script:
              - php /tmp/frosh-plugin-upload.phar plugin:validate ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip
        - stage: Store-Sync
          before_script: skip
          php: 7.3
          install:
              - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.1/frosh-plugin-upload.phar' -O /tmp/frosh-plugin-upload.phar
          script:
              - php /tmp/frosh-plugin-upload.phar plugin:update ${TRAVIS_BUILD_DIR}
        - stage: Store-Deploy
          before_script: skip
          php: 7.3
          install:
              - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.1/frosh-plugin-upload.phar' -O /tmp/frosh-plugin-upload.phar
              - cd /tmp && php /tmp/frosh-plugin-upload.phar plugin:zip:dir ${TRAVIS_BUILD_DIR} && mv ${PLUGIN_NAME}*.zip ${TRAVIS_BUILD_DIR}
          script:
              - php /tmp/frosh-plugin-upload.phar plugin:upload ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip

deploy:
  provider: releases
  api_key:
    secure: U2OcY4bAhmo+eoRJ6UJE2uRkPyx+FVpnqCYO9JvJKrNiEgrxttQLyUszz/wVjJ9or4doUyWQ2B2qsmzZHJZDT8nxG9MIbEy/F4ppJdOE0+pbRj3YXDlJp/BsrctyIq8mDMD93h43fBnl06Wyyx4AQDmrvZr0u+kqviVEh7nRgVar0UiUc7pWNCxUAebIvDE9mbBdktdHnfjCQ7Wq0Y/N1CMLeBw9W8LZiurnk5e629WWJcVkfiVaEQGCCxLVBcjpyjXJXUnoewcMPzLvEBK0HdCyWcy8cPiDKvQz/ll5Aut5x8GZlkLc2PoPOJNtgC93CavZq1N0wvlVr4a1qCw8utshrjD6m9d04jVFjfgtpkJrloMTPOxrOR0VbPf8PvzhRQUYHHSpB4wmZEBR0otnNRhxj+eUD46+NLQpSutIoQ78gKHeuT6GdS2REh6PZ/JphMubmTAb502ONfCOtiC6GOz2smAoeN5c9/eCJag9yYdtU/2OqJ3a6dJM/isua5G7Edq/KBy4pXXk8+9jK21kQ6VjAENHn5D1Yh6edf0EDWIdZRcdppyk3OyGqoLhqCF7yoRpz36cBpqTBk5XLmNwgfsaPvaGTLhBhwbCx7S0dIzVkYSMABK2ftQi+2p1nRPe71dIe46/w0etvdFXwjXiuCYE+DPoIN2NE9mjnp+6PzY=
  file: FroshPlatformAdminer-*.zip
  file_glob: true
  on:
    tags: true
